/**
 * Links to the OrcaSlicer filament presets published alongside the dataset API.
 *
 * The presets are generated by `ofd build` (see ofd/builder/exporters/orca_exporter.py)
 * and mirror the static API's path shape, so a preset URL is the API URL with
 * `api/v1` swapped for `orcaslicer`. Nothing is converted client-side — these are
 * plain download links.
 *
 * Every function returns null when PUBLIC_API_BASE_URL is unset. That is what
 * hides the download buttons in local editor mode, where the filament being
 * edited has not been published to the API yet and the link would 404.
 */
import { env } from '$env/dynamic/public';

function apiBase(): string | null {
	const base = env.PUBLIC_API_BASE_URL;
	if (!base) return null;
	return base.endsWith('/') ? base.slice(0, -1) : base;
}

/** Root of the published OrcaSlicer preset tree, or null when unconfigured. */
export function orcaBaseUrl(): string | null {
	const base = apiBase();
	return base ? `${base}/orcaslicer` : null;
}

/**
 * One filament's preset. `material` is upper-cased to match the API's path
 * segments, the same normalisation cloudProxy.ts applies to route params.
 */
export function orcaProfileUrl(brand: string, material: string, filament: string): string | null {
	const base = orcaBaseUrl();
	if (!base || !brand || !material || !filament) return null;
	return (
		`${base}/brands/${encodeURIComponent(brand)}` +
		`/materials/${encodeURIComponent(material.toUpperCase())}` +
		`/filaments/${encodeURIComponent(filament)}.json`
	);
}

/** A zip of every preset for one brand. */
export function orcaBundleUrl(brand: string): string | null {
	const base = orcaBaseUrl();
	if (!base || !brand) return null;
	return `${base}/bundles/${encodeURIComponent(brand)}.zip`;
}

/** Suggested filename for a downloaded preset, matching the name inside it. */
export function orcaProfileFilename(brandName: string, filamentName: string): string {
	return `${brandName} ${filamentName} (OFD).json`.replace(/[<>:"/\\|?*]/g, '_');
}
