/**
 * Links to the OrcaSlicer filament presets published alongside the dataset API.
 *
 * The presets are generated by `ofd build` (see ofd/builder/exporters/orca_exporter.py)
 * and mirror the static API's path shape, so a preset URL is the API URL with
 * `api/v1` swapped for `orcaslicer`. Nothing is converted client-side — these are
 * plain download links.
 *
 * Every function returns null when PUBLIC_API_BASE_URL is unset. That is what
 * hides the download buttons in local editor mode, where the filament being
 * edited has not been published to the API yet and the link would 404.
 *
 * They also return null for a filament the exporter skips. The exporter emits
 * nothing for a material with no credible OrcaSlicer base profile (PEEK, PPS,
 * PVDF and friends), so offering those a link would be offering a 404 — see
 * orcaMaterials.generated.ts for the mirrored rules.
 */
import { env } from '$env/dynamic/public';
import { ORCA_BASE_MATERIALS, ORCA_NAME_ONLY_RULES } from './orcaMaterials.generated';

const BASE_MATERIALS = new Set(ORCA_BASE_MATERIALS);

function apiBase(): string | null {
	const base = env.PUBLIC_API_BASE_URL;
	if (!base) return null;
	return base.endsWith('/') ? base.slice(0, -1) : base;
}

/**
 * Whether the exporter writes a preset for this filament — the client-side twin
 * of `ofd.builder.orca_mapping.resolve_base_profile` returning a base.
 *
 * `filamentName` matters only for materials that reach a base through a name
 * refinement (a PPA inheriting PPA-CF). Omitting it hides those rather than
 * risking a dead link, which is the safe direction to be wrong in.
 */
export function orcaCanExport(material: string, filamentName = ''): boolean {
	if (!material) return false;
	const type = material.toUpperCase();
	if (BASE_MATERIALS.has(type)) return true;

	const name = filamentName.toLowerCase();
	if (!name) return false;
	return ORCA_NAME_ONLY_RULES.some(
		(rule) => rule.materials.includes(type) && rule.pattern.test(name)
	);
}

/**
 * Whether a brand bundle is worth offering, given the brand's material types.
 *
 * The exporter only writes `bundles/{brand}.zip` for a brand with at least one
 * exported preset, so a brand of nothing but unmapped materials has no zip.
 * Filament names are not loaded on the brand page, so a name-only material
 * counts as a maybe here — an over-approximation that can only mislead for a
 * brand selling exclusively unfilled PPA and nothing else.
 */
export function orcaBrandCanExport(materials: readonly string[]): boolean {
	return materials.some((material) => {
		if (!material) return false;
		const type = material.toUpperCase();
		return (
			BASE_MATERIALS.has(type) || ORCA_NAME_ONLY_RULES.some((rule) => rule.materials.includes(type))
		);
	});
}

/** Root of the published OrcaSlicer preset tree, or null when unconfigured. */
export function orcaBaseUrl(): string | null {
	const base = apiBase();
	return base ? `${base}/orcaslicer` : null;
}

/**
 * One filament's preset, or null when none is published. `material` is
 * upper-cased to match the API's path segments, the same normalisation
 * cloudProxy.ts applies to route params.
 */
export function orcaProfileUrl(
	brand: string,
	material: string,
	filament: string,
	filamentName = ''
): string | null {
	const base = orcaBaseUrl();
	if (!base || !brand || !material || !filament) return null;
	if (!orcaCanExport(material, filamentName)) return null;
	return (
		`${base}/brands/${encodeURIComponent(brand)}` +
		`/materials/${encodeURIComponent(material.toUpperCase())}` +
		`/filaments/${encodeURIComponent(filament)}.json`
	);
}

/**
 * A zip of every preset for one brand, or null when the brand has none.
 * Pass the brand's material types so an all-unmapped brand gets no link.
 */
export function orcaBundleUrl(brand: string, materials: readonly string[] = []): string | null {
	const base = orcaBaseUrl();
	if (!base || !brand) return null;
	if (!orcaBrandCanExport(materials)) return null;
	return `${base}/bundles/${encodeURIComponent(brand)}.zip`;
}

/** Suggested filename for a downloaded preset, matching the name inside it. */
export function orcaProfileFilename(brandName: string, filamentName: string): string {
	return `${brandName} ${filamentName} (OFD).json`.replace(/[<>:"/\\|?*]/g, '_');
}
