// Generated by `ofd script generate_orca_materials` — do not edit by hand.
//
// Mirrors the exportability rules in ofd/builder/orca_mapping.py so the WebUI
// only offers a download link for a preset the exporter actually writes.
// tests/test_orca_exporter.py fails if this file drifts from the Python source.

/** Materials that are exportable on the material type alone. */
export const ORCA_BASE_MATERIALS: readonly string[] = [
	'ABS',
	'ASA',
	'BVOH',
	'CPE',
	'EVA',
	'HIPS',
	'PA11',
	'PA12',
	'PA6',
	'PA66',
	'PC',
	'PCTG',
	'PEBA',
	'PET',
	'PETG',
	'PHA',
	'PLA',
	'PP',
	'PVA',
	'SBS',
	'TPC',
	'TPE',
	'TPU'
];

/**
 * Materials with no default base that only become exportable when the filament
 * name matches — PPA reaching the filled PPA-CF/PPA-GF bases.
 */
export const ORCA_NAME_ONLY_RULES: readonly {
	pattern: RegExp;
	materials: readonly string[];
}[] = [
	{ pattern: /(?:^|[\s\-_(])(?:cf|carbon)(?:$|[\s\-_)])/i, materials: ['PPA'] },
	{ pattern: /(?:^|[\s\-_(])(?:gf|glass)(?:$|[\s\-_)])/i, materials: ['PPA'] }
];
