"""
Generate the WebUI's mirror of the OrcaSlicer exportability rules.

The exporter skips any filament whose material has no credible OrcaSlicer base
profile (see ofd/builder/orca_mapping.py). The WebUI has to make the same call
before it offers a download link, or it offers a 404. It cannot import the
Python rules, and it has to work offline in the local editor, so the rules are
mirrored into a generated TypeScript module instead of fetched from the API.

Run after changing ORCA_BASE_BY_MATERIAL or the name refinements:

    ofd script generate_orca_materials

`--check` verifies the checked-in file is current without writing it; that is
what tests/test_orca_exporter.py runs, so drift fails CI rather than shipping.
"""

import argparse
from pathlib import Path

from ofd.base import BaseScript, ScriptResult, register_script
from ofd.builder.orca_mapping import BASE_MATERIALS, NAME_ONLY_MATERIAL_RULES

OUTPUT_PATH = Path("webui/src/lib/utils/orcaMaterials.generated.ts")

HEADER = """// Generated by `ofd script generate_orca_materials` — do not edit by hand.
//
// Mirrors the exportability rules in ofd/builder/orca_mapping.py so the WebUI
// only offers a download link for a preset the exporter actually writes.
// tests/test_orca_exporter.py fails if this file drifts from the Python source.
"""


def _ts_str(value: str) -> str:
    """Single-quoted string literal, the style webui/.prettierrc enforces."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render() -> str:
    """Render the TypeScript module for the current Python rules."""
    materials = ",\n".join(f"\t{_ts_str(m)}" for m in sorted(BASE_MATERIALS))

    rules = []
    for source, extra in NAME_ONLY_MATERIAL_RULES:
        names = ", ".join(_ts_str(m) for m in sorted(extra))
        # 'i' is redundant — callers lower-case the name, as resolve_base_profile
        # does — but it keeps the rule correct if a caller forgets.
        rules.append(f"\t{{ pattern: /{source}/i, materials: [{names}] }}")
    rules_block = ",\n".join(rules)

    return f"""{HEADER}
/** Materials that are exportable on the material type alone. */
export const ORCA_BASE_MATERIALS: readonly string[] = [
{materials}
];

/**
 * Materials with no default base that only become exportable when the filament
 * name matches — PPA reaching the filled PPA-CF/PPA-GF bases.
 */
export const ORCA_NAME_ONLY_RULES: readonly {{
	pattern: RegExp;
	materials: readonly string[];
}}[] = [
{rules_block}
];
"""


@register_script
class GenerateOrcaMaterialsScript(BaseScript):
    name = "generate_orca_materials"
    description = "Regenerate the WebUI mirror of the OrcaSlicer exportability rules"

    def configure_parser(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument(
            "--check",
            action="store_true",
            help="Fail if the checked-in file is out of date instead of rewriting it",
        )

    def run(self, args: argparse.Namespace) -> ScriptResult:
        target = self.project_root / OUTPUT_PATH
        expected = render()
        current = target.read_text(encoding="utf-8") if target.exists() else None

        if current == expected:
            return ScriptResult(success=True, message=f"{OUTPUT_PATH} is up to date")

        if args.check:
            return ScriptResult(
                success=False,
                message=(
                    f"{OUTPUT_PATH} is out of date — run `ofd script generate_orca_materials`"
                ),
            )

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected, encoding="utf-8")
        return ScriptResult(success=True, message=f"Wrote {OUTPUT_PATH}")
